name: "Capture website as image"
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment-run:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        # 0 indicates all history
        fetch-depth: 0
    - name: setup aliyun oss if ossutil is used
      uses: manyuanrong/setup-ossutil@v2.0
      if: ${{ contains(github.event.comment.body, 'ossutil') }}
      with:
        endpoint: oss-cn-qingdao.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    - uses: nwtgck/actions-comment-run@v1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allowed-associations: '["OWNER"]'
